### ISSUE TITLE
[Suggection] Cache whether or not the block interaction should be blocked

### ISSUE THREAD

**Issue by Kasualix** [CanoeStudioOfficial/BlockInteractionMod#1]
https://github.com/CanoeStudioOfficial/BlockInteractionMod/blob/0b5be5a35432daeeedfa466f8919fc2fdd6e1150/src/main/java/com/cleanroommc/blockinteractionmod/Blockinteractionmod.java#L23
If the end-user/modpacker adds too many entries in the config, the iteration in `ArrayList#contains` will be quite expensive on performance, causing client/server lag on block interactions.
![image](https://github.com/CanoeStudioOfficial/BlockInteractionMod/assets/110756250/61ac5de7-9136-495b-8920-4e18cc966674)
If you feel sick on mixins, you can simply change the ArrayList to HashSet whose contains check is also quite fast.

**Comment by LonelyxiyaOVO** [comment]
[09790c3](https://github.com/CanoeStudioOfficial/BlockInteractionMod/commit/09790c3f0215b51e8da6106ba05f2336887b970b)
